erpc_tcp_transport.cpp: fix missing initializer for members of addrinfo
erpc/erpc_c/transports/erpc_tcp_transport.cpp: In member function ‘virtual erpc_status_t erpc::TCPTransport::connectClient()’:
erpc/erpc_c/transports/erpc_tcp_transport.cpp:89:33: error: missing initializer for member ‘addrinfo::ai_family’ [-Werror=missing-field-initializers]
     struct addrinfo hints = { 0 };
                                 ^
erpc/erpc_c/transports/erpc_tcp_transport.cpp:89:33: error: missing initializer for member ‘addrinfo::ai_socktype’ [-Werror=missing-field-initializers]
erpc/erpc_c/transports/erpc_tcp_transport.cpp:89:33: error: missing initializer for member ‘addrinfo::ai_protocol’ [-Werror=missing-field-initializers]
erpc/erpc_c/transports/erpc_tcp_transport.cpp:89:33: error: missing initializer for member ‘addrinfo::ai_addrlen’ [-Werror=missing-field-initializers]
erpc/erpc_c/transports/erpc_tcp_transport.cpp:89:33: error: missing initializer for member ‘addrinfo::ai_addr’ [-Werror=missing-field-initializers]
erpc/erpc_c/transports/erpc_tcp_transport.cpp:89:33: error: missing initializer for member ‘addrinfo::ai_canonname’ [-Werror=missing-field-initializers]
erpc/erpc_c/transports/erpc_tcp_transport.cpp:89:33: error: missing initializer for member ‘addrinfo::ai_next’ [-Werror=missing-field-initializers]